# the name of this particular app, remember that we allow you
# to create a project out of 1 or more apps, so this gives our
# Laravel app a name...
name: app
type: php:8.0 # SSIA
build:
  # Same as before, this alerts our system to look for a composer.json
  # or composer.lock file and install the dependencies defined therein
  flavor: composer
# basic web configuration for this particular app.  Laravel apps have a
# "public" folder that serves as the web docroot.
web:
  locations:
    "/":
      root: "public"
      index:
        - index.php
      allow: true
      passthru: "/index.php"
# How much disk space to allot to this app.  
disk: 2048
# This is where you define your writable file system paths.  the keys are the
# paths in your app that need to be writable/uploadable.  The values are always
# going to be named "shared:files/$WHATEVER_HERE", where "WHATEVER_HERE" can be
# any arbitrary identifier.
mounts:
  # Laravel uses a directory off the root called "storage" for logs and cache.
  # We don't support specifying nested directories so make these directories
  # flat beyond "shared:files"
  "/storage/app/public": "shared:files/app-public"
  "/storage/framework/views": "shared:files/framework-views"
  "/storage/framework/sessions": "shared:files/framework-sessions"
  "/storage/framework/cache": "shared:files/framework-cache"
  "/storage/logs": "shared:files/logs"
  # And another cache directory here.
  "/bootstrap/cache": "shared:files/bootstrap_cache"
relationships:
  database: "pgsql:postgresql"