
<?php

return [
    'prices_q' => "What are the prices of your photo shoot and which promotions could we take advantage of?",
    'after_services_q' => "What are we going to obtain after the wedding?",
    "how_much_q" => "How much photos you're going to take? Is it possible to order from you also the re-print of the photos?",
    'prices_a' => "The prices of the photo shoot, compared to the level of professionalism and quality of the products I offer, I would say that they are really excellent! To make a detailed estimate it is necessary that I can receive all the necessary information from the spouses, and then make an appointment at my studio, to adjust my base price, under which you cannot go down, varying, with respect to the needs and desires of the couple who want to plan their “Big day” perfectly. The discounts that I can bestow consist, more than anything else, of \"Wedding services / products\" or personalized gifts which in themselves are very useful in lowering your wedding budget. Price bargaining does not exist precisely because it is I myself who try to satisfy my customers as best as possible, without giving up the two cornerstones of my work: quality and high professionalism in managing the whole event.",
    'after_services_a' => "About four months after the wedding you can come to my studio to view the selected photos (contact sheets) that will be included in your classic album or digital photo book. Or, alternatively, you will totally leave the task of creating the album with the photos that I think are most artistic, exciting and that tell the story of that day even in the most accurate details, to me. So after about a month / two, you will receive your album with the DVD of the photos and any accessories for those who wish (smaller photo books for parents and / or witnesses, photo box, suitcase, photographic panels, etc.)",
    "how_much_a" => "At your wedding I will take a lot of shots and once, select the photos and work, on the DVD that I will deliver to you, I will put about 500 photos, or more. including those that you will choose for the photo book or classic album. The photos will all be in high resolution subject to printing, for this reason, those who wish, can have reprints (in various formats) or individual photographic panels of furniture, in various materials (forex, falcon, wood, canvas, etc.)"
];